language: php

services:
  - docker

matrix:
  include:
  - name: "PHP 7.1"
    env: DOCKER_IMAGE=7.1-alpine
  - name: "PHP 7.1 wkhtmltopdf"
    env: DOCKER_IMAGE=7.1-alpine-wkhtmltopdf
  - name: "PHP 7.2"
    env: DOCKER_IMAGE=7.2-alpine
  - name: "PHP 7.2 wkhtmltopdf"
    env: DOCKER_IMAGE=7.2-alpine-wkhtmltopdf
  - name: "PHP 7.3"
    env: DOCKER_IMAGE=7.3-alpine
  - name: "PHP 7.3 wkhtmltopdf"
    env: DOCKER_IMAGE=7.3-alpine-wkhtmltopdf

before_script:
  - docker build -t fireworkweb/app:$DOCKER_IMAGE $DOCKER_IMAGE

script:
  - docker run -it --rm $DOCKER_IMAGE php -v
