language: minimal

services:
  - docker

matrix:
  include:
  - name: "PHP 7.1"
    env: DOCKER_IMAGE=7.1-alpine
  - name: "PHP 7.2"
    env: DOCKER_IMAGE=7.2-alpine
  - name: "PHP 7.3"
    env: DOCKER_IMAGE=7.3-alpine

before_script:
  - docker build -t fireworkweb/app:$DOCKER_IMAGE $DOCKER_IMAGE
  - docker build -t fireworkweb/app:$DOCKER_IMAGE-wkhtmltopdf $DOCKER_IMAGE-wkhtmltopdf

script:
  - docker run -it --rm fireworkweb/app:$DOCKER_IMAGE php -v
  - docker run -it --rm fireworkweb/app:$DOCKER_IMAGE-wkhtmltopdf php -v
