name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 7.1, 7.2, 7.3, 7.4 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build images
      run: |
        docker build --pull -t fireworkweb/php:${{ matrix.version }} ${{ matrix.version }}
        docker build --pull -t fireworkweb/php:${{ matrix.version }}-prod ${{ matrix.version }}-prod
        docker build -t fireworkweb/php:${{ matrix.version }}-wkhtmltopdf ${{ matrix.version }}-wkhtmltopdf
        docker build -t fireworkweb/php:${{ matrix.version }}-wkhtmltopdf-prod ${{ matrix.version }}-wkhtmltopdf-prod

    - name: Build images nginx
      if: matrix.version == '7.4'
      run: |
        docker build -t fireworkweb/php:${{ matrix.version }}-nginx ${{ matrix.version }}-nginx
        docker build -t fireworkweb/php:${{ matrix.version }}-nginx-prod ${{ matrix.version }}-nginx-prod
        docker build -t fireworkweb/php:${{ matrix.version }}-nginx-wkhtmltopdf ${{ matrix.version }}-nginx-wkhtmltopdf
        docker build -t fireworkweb/php:${{ matrix.version }}-nginx-wkhtmltopdf-prod ${{ matrix.version }}-nginx-wkhtmltopdf-prod

    - name: Test docker images
      run: |
        docker run fireworkweb/php:${{ matrix.version }} php -v
        docker run fireworkweb/php:${{ matrix.version }} composer -V
        docker run -e ASUSER=1000 fireworkweb/php:${{ matrix.version }} php -v
        docker run -e ASUSER=1000 fireworkweb/php:${{ matrix.version }} composer -V

        docker run fireworkweb/php:${{ matrix.version }} php -m
        docker run -e ENABLE_XDEBUG=true fireworkweb/php:${{ matrix.version }} php -m

    - name: Push to Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fireworkweb/php:${{ matrix.version }}
        docker push fireworkweb/php:${{ matrix.version }}-prod
        docker push fireworkweb/php:${{ matrix.version }}-wkhtmltopdf
        docker push fireworkweb/php:${{ matrix.version }}-wkhtmltopdf-prod

    - name: Push to Hub nginx
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.version == '7.4'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fireworkweb/php:${{ matrix.version }}-nginx
        docker push fireworkweb/php:${{ matrix.version }}-nginx-prod
        docker push fireworkweb/php:${{ matrix.version }}-nginx-wkhtmltopdf
        docker push fireworkweb/php:${{ matrix.version }}-nginx-wkhtmltopdf-prod
